# Generated by Django 5.2.14 on 2026-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loker',
            fields=[
                ('id_loker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('industri', models.CharField(blank=True, max_length=255, null=True)),
                ('tipe', models.CharField(blank=True, max_length=100, null=True)),
                ('kategori', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_post', models.CharField(blank=True, max_length=100, null=True)),
                ('berlaku_hingga', models.CharField(blank=True, max_length=100, null=True)),
                ('perusahaan', models.CharField(blank=True, max_length=255, null=True)),
                ('website_perusahaan', models.TextField(blank=True, null=True)),
                ('logo_perusahaan', models.TextField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('negara', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('gaji_min', models.CharField(blank=True, max_length=100, null=True)),
                ('gaji_max', models.CharField(blank=True, max_length=100, null=True)),
                ('gaji_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('gaji_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('pengalaman_bulan', models.CharField(blank=True, max_length=100, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tentang_perusahaan', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loker',
            },
        ),
    ]
